stages:
  - build
  - deploy

build-front:
  stage: build
  script:
    - cd front
    - docker build -t ${CI_REGISTRY_IMAGE}/front:${CI_COMMIT_REF_SLUG} .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker push ${CI_REGISTRY_IMAGE}/front:${CI_COMMIT_REF_SLUG}
  tags:
    - lab-ia
  retry: 2

build-back:
  stage: build
  script:
    - cd back
    - docker build -t ${CI_REGISTRY_IMAGE}/back:${CI_COMMIT_REF_SLUG} .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker push ${CI_REGISTRY_IMAGE}/back:${CI_COMMIT_REF_SLUG}
  tags:
    - lab-ia
  retry: 2

deploy:
  stage: deploy
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker-compose pull
    - docker-compose up -d
  tags:
    - lab-ia
  retry: 2